datasets:
  name: NIR_VISv2
  root: /YOUR/DATASETS/PATH/NIR_VISv2/
  size: 128
train: 
  model: LightCNN-29v4
  lr: 0.001
  pre_lr: 0.02
  moentum: 0.9
  weight_decay: 0.0001
  batch_size: 186
  workers: 8
  pre_epoch: 5
  dropout_rate: 0.6
  max_dropout: 0.95
  adjust_lr: 30
  adjust_dropout: 5
  epochs: 80
  val_frep: 3
  sub_channels: [ 0 ]
  resume: PRETRAIN/WEIGHT/PATH
  protocols: [datasets/NIR-VISv2/Protocol/nir_train_dev.txt, datasets/NIR-VISv2/Protocol/vis_train_dev.txt]
val:
  gallery: [datasets/NIR-VISv2/Protocol/vis_gallery_dev.txt]
  probe: [datasets/NIR-VISv2/Protocol/nir_probe_dev.txt]
  weight: YOUR/CHECKPOINT/PATH
logs:
  output_path: logs/NIR-VISv2/
  print_freq: 50
avih:
  resume: YOUR/CHECKPOINT/PATH
  alpha: 0.02
  num_iter: 800
  batch_size: 150
  protocols: [datasets/NIR-VISv2/Protocol/nir_probe_dev.txt, datasets/NIR-VISv2/Protocol/vis_gallery_dev.txt]
  adv_size: [128,128]