datasets:
  name: Tufts
  root: /data/datasets/Tufts/
  size: 128
  num_classes: 90
train: 
  model: LightCNN-29v4
  lr: 0.001
  pre_lr: 0.02
  moentum: 0.9
  pre_epoch: 5
  weight_decay: 0.0001
  batch_size: 186
  workers: 8
  dropout_rate: 0.6
  max_dropout: 0.95
  adjust_lr: 30
  adjust_dropout: 5
  epochs: 80
  val_frep: 3
  sub_channels: [ 0 ]
  resume: model/weight/LightCNN-V4_checkpoint.pth.tar
  protocols: [datasets/Tufts/Protocol/train.txt]
val:
  gallery: [datasets/Tufts/Protocol/gallery_small.txt]
  probe: [datasets/Tufts/Protocol/probe.txt]
  weight: best_weight/Tufts_92.857.ckpt
  root: logs/Tufts/2024-04-10/1000
logs:
  output_path: logs/Tufts/
  print_freq: 50
avih:
  resume: best_weight/Tufts_92.857.ckpt
  alpha: 0.02
  num_iter: 1200
  batch_size: 150
  protocols: [datasets/Tufts/Protocol/gallery_small.txt, datasets/Tufts/Protocol/probe.txt]
  adv_channel: 3
  adv_size: [128,128]